# Header
menu:
  主页: /
  目录: /archives
  -关于我-: /about

# SubNav
subnav:
  #rss: https://www.baidu.com
  zhihu: https://www.zhihu.com/people/zhi-hui-64-54/answers
  bilibili: https://space.bilibili.com/20259914
  weibo: http://weibo.com/u/1679186305
  github: https://github.com/peng-zhihui
  #douban: "#"
  mail: mailto:david.pzh@qq.com
  # rss: http://i.youku.com/u/UNTAzODc3NDM2
  # facebook: "#"
  # google: "#"
  # linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: 继续阅读
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢请我喝可乐~'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/pay/alipay.jpg
# 微信二维码图片地址
weixin: /assets/pay/wxpay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
google_analytics: ''
baidu_analytics: '49ce7d4aa41c5f61c6e62e401abd4ae1'
favicon: /favicon.png

#你的头像url
avatar:  /logo.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
# changyan_appid: 'cyt6Gkc5O'
# changyan_conf: 'prod_b529cf1fb7e2e8e62719e1f6a16cf8df'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#8、Valine
valine:
  appid: guYIgTlqxF5PFg8JbFhmuaSj-gzGzoHsz #Leancloud应用的appId
  appkey: HVnAVp6RcYTXlgyDcjOfCF6n #Leancloud应用的appKey
  verify: false #验证码
  notify: true #评论回复提醒
  avatar: mm #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 欢迎留下你的评论~ #评论框占位符


# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  friends: '友链'
  innerArchive: '搜索文章 >>'
  aboutme: false

friends:  
  Arduino中文网: http://www.arduino.cn/
  创友老陈: http://www.csksoft.net/blog/
  同门师弟: https://vkwk.space/
  马攀博客: https://mapan.tech/
  炫Q香蕉派: https://mikuq.com/
  myyerrol's blog: http://myyerrol.io/
  阿正的个人站: http://wenzheng.club/
  # 友情链接4: http://localhost:4000/
  # 友情链接5: http://localhost:4000/
  # 友情链接6: http://localhost:4000/

aboutme: 一只栩栩如生的极客儿