baseURL: 'https://zhdylan.github.io'
enableEmoji: true
frontmatter:
  date:
    - date
  spoiler:
    - spoiler
languageCode: 'en-us'
title: 'blogging'
author: 'Dylan Zhang'

Params:
  author: 'Dylan Zhang'
  description: "Just some random, potentially useful, things I've written about."
  social:
    email: 'dongdongzhang@outlook.com'
    github: 'zhdylan'
    instagram: 'gracie_and_oliver'
    linkedin: 'dd1zhang'
    twitter: 'dd1zhang'
